### ISSUE TITLE
🧊冰宝❤️🧡💛💚🩵💙

### ISSUE THREAD

**Issue by chanbengz** [IceLocke/CS323-Compilers#1]
你是我的阳光☀️，我的唯一阳光🌞 你让我在天空灰暗时依然快乐😊 亲爱的💕，你永远不会知道我有多爱你❤️ 请不要带走我的阳光🙏那个夜晚🌌亲爱的，当我躺着入睡😴 我梦见我抱着你在我的怀里💭 当我醒来亲爱的，我发现我错了😢 所以我低下头哭泣😭你是我的阳光☀️，我的唯一阳光🌞 你让我在天空灰暗时依然快乐😇 亲爱的💖，你永远不会知道我有多爱你💘 请不要带走我的阳光🚫☀️

**Comment by wLUOw** [comment]
> 你是我的阳光☀️，我的唯一阳光🌞 你让我在天空灰暗时依然快乐😊 亲爱的💕，你永远不会知道我有多爱你❤️ 请不要带走我的阳光🙏那个夜晚🌌亲爱的，当我躺着入睡😴 我梦见我抱着你在我的怀里💭 当我醒来亲爱的，我发现我错了😢 所以我低下头哭泣😭你是我的阳光☀️，我的唯一阳光🌞 你让我在天空灰暗时依然快乐😇 亲爱的💖，你永远不会知道我有多爱你💘 请不要带走我的阳光🚫☀️

唐🍬

**Comment by IceLocke** [comment]
> 你是我的阳光☀️，我的唯一阳光🌞 你让我在天空灰暗时依然快乐😊 亲爱的💕，你永远不会知道我有多爱你❤️ 请不要带走我的阳光🙏那个夜晚🌌亲爱的，当我躺着入睡😴 我梦见我抱着你在我的怀里💭 当我醒来亲爱的，我发现我错了😢 所以我低下头哭泣😭你是我的阳光☀️，我的唯一阳光🌞 你让我在天空灰暗时依然快乐😇 亲爱的💖，你永远不会知道我有多爱你💘 请不要带走我的阳光🚫☀️

糖b

**Comment by chanbengz** [comment]
冰冰宝贝中秋快乐么么哒💋
